import React from "react";
import profile from "../../assets/profilepicture.png";
import AdminOptionsSvg from "../../svg-component/optionsSvg";

const AdminnTableData = () => {
  return {
    tableData: [
      {
        id: 1,
        picture: profile,
        name: "Mofe Damijo",
        email: "Mdamijo@gmail.com",
        accountBal: "N189,500",
        tierLvl: "Tier 0",
        status: "Active",
        accounNo: "8155320900",
        action: <AdminOptionsSvg />,
      },

      {
        id: 2,
        picture: profile,
        name: "Mofe Damijo",
        email: "Mdamijo@gmail.com",
        accountBal: "N189,500",
        tierLvl: "Tier 0",
        status: "Inactive",
        accounNo: "8155320900",
        action: <AdminOptionsSvg />,
      },
      {
        id: 3,
        picture: profile,
        name: "Mofe Damijo",
        email: "Mdamijo@gmail.com",
        accountBal: "N189,500",
        tierLvl: "Tier 0",
        status: "Dormant",
        accounNo: "8155320900",
        action: <AdminOptionsSvg />,
      },
      {
        id: 4,
        picture: profile,
        name: "Mofe Damijo",
        email: "Mdamijo@gmail.com",
        accountBal: "N189,500",
        tierLvl: "Tier 0",
        status: "Active",
        accounNo: "8155320900",
        action: <AdminOptionsSvg />,
      },
      {
        id: 5,
        picture: profile,
        name: "Mofe Damijo",
        email: "Mdamijo@gmail.com",
        accountBal: "N189,500",
        tierLvl: "Tier 0",
        status: "Inactive",
        accounNo: "8155320900",
        action: <AdminOptionsSvg />,
      },
      {
        id: 6,
        picture: profile,
        name: "Mofe Damijo",
        email: "Mdamijo@gmail.com",
        accountBal: "N189,500",
        tierLvl: "Tier 0",
        status: "Active",
        accounNo: "8155320900",
        action: <AdminOptionsSvg />,
      },

      {
        id: 7,
        picture: profile,
        name: "Mofe Damijo",
        email: "Mdamijo@gmail.com",
        accountBal: "N189,500",
        tierLvl: "Tier 0",
        status: "Inactive",
        accounNo: "8155320900",
        action: <AdminOptionsSvg />,
      },
      {
        id: 8,
        picture: profile,
        name: "Mofe Damijo",
        email: "Mdamijo@gmail.com",
        accountBal: "N189,500",
        tierLvl: "Tier 0",
        status: "Dormant",
        accounNo: "8155320900",
        action: <AdminOptionsSvg />,
      },
      {
        id: 9,
        picture: profile,
        name: "Mofe Damijo",
        email: "Mdamijo@gmail.com",
        accountBal: "N189,500",
        tierLvl: "Tier 0",
        status: "Active",
        accounNo: "8155320900",
        action: <AdminOptionsSvg />,
      },
      {
        id: 10,
        picture: profile,
        name: "Mofe Damijo",
        email: "Mdamijo@gmail.com",
        accountBal: "N189,500",
        tierLvl: "Tier 0",
        status: "Inactive",
        accounNo: "8155320900",
        action: <AdminOptionsSvg />,
      },
    ],
  };
};

export default AdminnTableData;
